# Generated by Django 3.2.25 on 2026-03-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0003_auto_20260315_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_numb_students',
        ),
    ]
