# Generated by Django 3.2.25 on 2026-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0004_remove_course_max_numb_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab'), ('Theory+Lab', 'Theory + Lab')], default='Theory', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='equipment_required',
            field=models.CharField(blank=True, help_text='Required equipment for AI/ML courses', max_length=100),
        ),
    ]
