# Generated by Django 3.2.25 on 2026-03-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0005_auto_20260315_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='equipment_available',
            field=models.CharField(blank=True, help_text='Available equipment in this room', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Classroom', 'Classroom'), ('Lab', 'Lab'), ('Computer Lab', 'Computer Lab'), ('AI Lab', 'AI Lab'), ('ML Lab', 'ML Lab'), ('DS Lab', 'DS Lab')], default='Classroom', max_length=20),
        ),
    ]
