# Generated by Django 3.2.25 on 2026-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0006_auto_20260315_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='max_courses_per_semester',
            field=models.IntegerField(default=3, help_text='Maximum courses this instructor can handle'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='specialization',
            field=models.CharField(blank=True, help_text='AI/ML specialization area', max_length=50),
        ),
    ]
