# Generated by Django 3.2.25 on 2026-04-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0007_auto_20260315_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='strength',
            field=models.IntegerField(default=30, help_text='Number of students in this section'),
        ),
    ]
