# Generated by Django 3.2.25 on 2026-04-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0008_section_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('batch_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time_seconds', models.FloatField(default=0.0)),
                ('fitness_score', models.FloatField(default=0.0)),
                ('total_entries', models.IntegerField(default=0)),
                ('conflicts', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Only one generation should be active')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_batch', models.CharField(default='default', help_text='Batch ID for this generation run', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this entry currently active')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.instructor')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.meetingtime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.section')),
            ],
            options={
                'ordering': ['meeting_time__day', 'meeting_time__time', 'section__section_id'],
                'unique_together': {('meeting_time', 'instructor'), ('meeting_time', 'room'), ('meeting_time', 'section')},
            },
        ),
    ]
