# Generated by Django 3.2.25 on 2026-04-13 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0009_generationlog_timetableentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetadata',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=20, unique=True)),
                ('model_path', models.CharField(help_text='Path to saved model file', max_length=255)),
                ('model_type', models.CharField(choices=[('LogisticRegression', 'Logistic Regression'), ('DecisionTree', 'Decision Tree'), ('RandomForest', 'Random Forest')], default='LogisticRegression', max_length=50)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('training_samples', models.IntegerField(default=0, help_text='Number of samples used for training')),
                ('accuracy', models.FloatField(blank=True, help_text='Model accuracy on validation set', null=True)),
                ('feature_columns', models.JSONField(default=list, help_text='List of feature column names used')),
                ('is_active', models.BooleanField(default=False, help_text='Currently active model for predictions')),
            ],
            options={
                'verbose_name': 'ML Model Metadata',
                'verbose_name_plural': 'ML Model Metadata',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTimetableData',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15)),
                ('time_slot', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_generation_batch', models.CharField(blank=True, help_text='Generation batch ID this data came from', max_length=50, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_assignments', to='SchedulerApp.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_assignments', to='SchedulerApp.instructor')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_assignments', to='SchedulerApp.meetingtime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_assignments', to='SchedulerApp.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_assignments', to='SchedulerApp.section')),
            ],
            options={
                'verbose_name': 'Historical Timetable Data',
                'verbose_name_plural': 'Historical Timetable Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15)),
                ('preferred_time', models.CharField(max_length=50)),
                ('preference_score', models.FloatField(default=0.5, help_text='ML-learned preference score (0 = low preference, 1 = high preference)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(default=0.0, help_text='Model confidence in this prediction', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('frequency_count', models.IntegerField(default=0, help_text='How many times instructor has been assigned this slot historically')),
                ('model_version', models.CharField(default='1.0', help_text='Version of ML model used', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='SchedulerApp.instructor')),
            ],
            options={
                'verbose_name': 'Faculty Preference',
                'verbose_name_plural': 'Faculty Preferences',
                'ordering': ['instructor', '-preference_score'],
            },
        ),
        migrations.AddIndex(
            model_name='historicaltimetabledata',
            index=models.Index(fields=['instructor', 'day', 'time_slot'], name='SchedulerAp_instruc_a61ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaltimetabledata',
            index=models.Index(fields=['source_generation_batch'], name='SchedulerAp_source__a590e4_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypreference',
            index=models.Index(fields=['instructor', 'preferred_day'], name='SchedulerAp_instruc_40c80f_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypreference',
            index=models.Index(fields=['preference_score'], name='SchedulerAp_prefere_9d9366_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facultypreference',
            unique_together={('instructor', 'preferred_day', 'preferred_time')},
        ),
    ]
