# Generated by Django 3.2.25 on 2026-04-13 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0010_auto_20260413_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictLog',
            fields=[
                ('conflict_id', models.AutoField(primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('room_conflict', 'Room Double Booking'), ('faculty_conflict', 'Faculty Double Booking'), ('section_conflict', 'Section Double Booking'), ('capacity_violation', 'Room Capacity Insufficient'), ('same_course_same_day', 'Same Course Multiple Times Same Day'), ('consecutive_classes', 'Too Many Consecutive Classes')], max_length=30)),
                ('message', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_method', models.CharField(blank=True, choices=[('manual', 'Manual Fix'), ('auto_fix', 'Auto Fix'), ('regenerate', 'Full Regeneration')], max_length=20)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='conflict_details',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field storing conflict information'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='entry_type',
            field=models.CharField(choices=[('auto', 'Auto Generated'), ('manual', 'Manual Entry'), ('hybrid', 'Hybrid (Auto + Manual Adjust)')], default='auto', help_text='How this entry was created', max_length=20),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='has_conflict',
            field=models.BooleanField(default=False, help_text='Whether this entry has a conflict with others'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked entries are preserved during partial regeneration'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='modified_by',
            field=models.CharField(blank=True, help_text='User who last modified', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='preference_score',
            field=models.FloatField(default=0.5, help_text='Cached preference score for this faculty-day-time combination', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['generation_batch', 'is_active'], name='SchedulerAp_generat_d25d35_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['has_conflict'], name='SchedulerAp_has_con_31a04c_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['is_locked'], name='SchedulerAp_is_lock_99fa0a_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['instructor', 'meeting_time'], name='SchedulerAp_instruc_c4d38f_idx'),
        ),
        migrations.AddField(
            model_name='conflictlog',
            name='conflicting_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicting_with', to='SchedulerApp.timetableentry'),
        ),
        migrations.AddField(
            model_name='conflictlog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='SchedulerApp.timetableentry'),
        ),
        migrations.AddIndex(
            model_name='conflictlog',
            index=models.Index(fields=['entry', 'is_resolved'], name='SchedulerAp_entry_i_50ff81_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictlog',
            index=models.Index(fields=['conflict_type'], name='SchedulerAp_conflic_ce6ca7_idx'),
        ),
    ]
